Repository real-fake-spaceshop/real-fake-spaceshop, pull requests merged in 2019-01, with the labels that each got.

#24 Bug fix
  server/db/models/index.js
  server/db/models/order.js
  server/db/models/product.js
  server/db/models/user.js
Labels: bug

#36 Seed testing
  script/seed.js
  script/seed.spec.js
Labels: testing

#38 Bug fix2
  server/db/models/order.spec.js
  server/db/models/product.spec.js
  server/db/models/user.js
  server/db/models/user.spec.js
Labels: bug, testing

#49 Fix landing page image URL
  README.md
  client/components/landing-page.js
Labels: bug

#54 feat(Material-UI):Material UI Implemented
  client/components/navbar.js
  client/index.js
  package-lock.json
  package.json
  public/index.html
Labels: enhancement

#53 Order quantities
  script/seed.js
  script/seed.spec.js
  server/db/models/index.js
  server/db/models/orderLineItem.js
  server/db/models/orderLineItem.spec.js
Labels: enhancement

#57 feature (api routes): created route for POST '/api/products'. Resolve…
  server/api/products.js
Labels: enhancement

#58 testing (product api routes): Created product api route tests. Resolve #50
  server/api/products.spec.js
Labels: testing

#71 feature (all products component): added route, almost done with compo…
  client/components/all-products.js
  client/components/index.js
  client/routes.js
Labels: enhancement

#73 Fixed seeding bug
  client/components/all-products.js
  script/seed.js
Labels: bug

#78 Refactor Product list
  client/components/product-list.jsx
  client/components/shopping-cart.jsx
Labels: chore

#82 feature (product catalogue): basic functionality complete. Resolve #21
  client/components/all-products.js
Labels: enhancement

#90 fix(landing-page): Landing page now available while logged in
  client/components/landing-page.js
  client/routes.js
Labels: bug

#92 Finish Order API
  server/api/orders.js
  server/api/orders.spec.js
Labels: enhancement

#98 Mergify Config update
  .mergify.yml
Labels: chore

#97 Signup fix
  client/components/index.js
  client/components/navbar.js
  client/components/navbar.jsx
  client/routes.js
  public/images/elon.jpg
  script/seed.js
Labels: bug

#99 Error notification
  client/app.js
  client/components/landing-page.jsx
  client/components/notifier.jsx
  client/components/notifier.spec.js
  client/routes.js
  client/store/index.js
  client/store/snacks.js
  client/store/snacks.spec.js
  package-lock.json
  package.json
Labels: enhancement

#111 Login page
  client/components/auth-form.js
  client/components/index.js
  client/components/login-page.jsx
  client/components/shopping-cart.jsx
  client/components/signup-page.jsx
  client/routes.js
Labels: enhancement

#118 feature (product catalogue): filter functionality. Resolve #12
  client/components/all-products.js
Labels: enhancement

#120 fix (product model): fixed price sequelize type to INTEGER. Resolve #51
  server/db/models/product.js
  server/db/models/product.spec.js
  server/db/models/user.js
Labels: chore

#121 Checkout
  client/components/checkout-page/checkout-page.jsx
  client/components/checkout-page/customer-info.jsx
  client/components/single-product.jsx
  client/store/stripe.js
  script/seed.js
  server/api/stripe.js
  server/db/models/user.js
Labels: enhancement

#124 Signup validation
  client/components/login-page.jsx
  client/components/signup-page.jsx
  client/store/user.js
Labels: bug

#125 fix(catalogue) its pretty now
  client/components/all-products.js
  client/styles.js
Labels: enhancement

#122 fix(add-to-cart): Change 'Add to cart' button to increase quantity by 1
  .travis.yml
  client/components/single-product.jsx
  client/store/singleProduct.js
Labels: bug

#130 fix(login): Fix cart not loading on login.
  client/components/login-page.jsx
  client/routes.js
  server/auth/index.js
Labels: bug
